#!/bin/bash

declare -F nvm
if [ $? -ne 0 ]; then
	export NVM_DIR=${HOME}/.nvm
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
fi

declare -F nvm
if [ $? -ne 0 ]; then
	echo "ERROR: nvm function undefined."
else
	echo "Running nvm install ..."
	nvm install && nvm use
fi

echo "Updating npm ..."
npm install -g npm

echo "Running composer install (root) ..."
composer install

# Clear the old boostrap/cache/compiled.php
echo "Running php artisan clear-compiled ... "
php artisan clear-compiled

# Recreate boostrap/cache/compiled.php
echo "Running php artisan optimize ... "
php artisan optimize

# Migrate any database changes
echo "Running php artisan migrate ... "
php artisan migrate

echo "Running npm ci ... "
npm ci

echo "Running npm run prod ... "
npm run prod

echo "Running php artisan route:clear ... "
php artisan route:clear

echo "Running php artisan route:cache ... "
php artisan route:cache

echo "Running php artisan config:clear ... "
php artisan config:clear

echo "Running php artisan config:cache ... "
php artisan config:cache


